### ISSUE TITLE
How to update DAGs without building a new Airflow Docker image?

### ISSUE THREAD

**Issue by Minyus** [astronomer/airflow-chart#94]
According to the [README.md](https://github.com/apache/airflow/tree/master/chart#updating-dags), 

> The recommended way to update your DAGs with this chart is to build a new docker image with the latest code

Would it be possible to update DAGs without building a new Airflow Docker image?

**Comment by schnie** [comment]
Hey @Minyus, this is the approach we've taken since we need to also allow all of our customers to update os packages and python packages, in addition to the DAGs.

This chart does not have support for it yet, but there are some folks discussing it in the official apache project. It could absolutely be done and we'd need to support the traditional git fetch, or rsync style of DAG deployment.

How would you like to ideally be able to deploy your DAGs?

**Comment by Minyus** [comment]
Thanks for your reply, @schnie .
Noted.
The following options would be convenient. 

- Upload a zip file including .py files in the Airflow web UI
- Upload a .py file in the Airflow web UI
- HTTP request to post the Python code to the server
- `rsync -r` to a directory in the server

**Comment by danielhoherd** [comment]
We have handled this with git-sync, nfs, and are about to release a dag-only deploy feature.
